services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: vk
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5555:5432"
    volumes:
      - ./docker-scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql